version: '2'
services:
  db:
    image: jobportal-db:latest
  
  backend:
    image: jobportal-backend:1.0.1
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
